name: Priva Proxy
version: v0.0.5
slug: priva-proxy
description: Scrape Vasim Energy usage from Priva Operator portal
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
ports:
  3000/tcp: 3000
options:
  email:
  password:
schema:
  email: email
  password: password
