name: Priva Proxy
version: v1.1.1
slug: priva-proxy
description: Scrape Vasim Energy usage from Priva Operator portal
url: https://github.com/10KB/vasim-energy/
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
ports:
  3000/tcp: 3000
options:
  email: null
  password: null
  log_level: info
schema:
  email: email
  password: password
  log_level: list(info|http|debug)
