name: 'Bump Version'

on:
  push:
    branches:
      - 'master'

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: ${{ github.ref }}
      - run: cat ./priva-proxy/package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          skip-commit: 'true'
          skip-tag: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'priva-proxy'

      - run: cat ./priva-proxy/package.json

      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

      - name: Bump version in config.yaml for Home Assistant addon
        uses: mikefarah/yq@v4.34.1
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        with:
          cmd: yq e -i '.version = strenv(NEW_TAG)' ./priva-proxy/config.yaml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Finish ${{ steps.version-bump.outputs.newTag }}'


